name: Publish to npm

on:
  push:
    branches: main

jobs:
  
  build:
    runs-on: ubuntu-latest

    environment:
      name: this
      url: https://github.com/ka9an/denopendabot

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v0.1.8
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: bun install
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
