name: Publish to npm

on:
  push:
    branches: main

jobs:
  
  build:
    runs-on: ubuntu-latest

    environment:
      name: this
      url: https://github.com/ka9an/denopendabot

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v0.1.8
      - uses: actions/setup-node@v3
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

